--Selecting all to view tables from excel file
SELECT *
FROM Energyproject..['coal-electricity-per-capita$']
WHERE Energyproject..['coal-electricity-per-capita$'].Entity <> 'Africa' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'Asia' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'Central African Republic' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'Democratic Republic of Congo' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'Europe' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'European Union (27)' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'High-income countries' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'Hong Kong' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'Low-income countries' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'Lower-middle-income countries' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'North America' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'South America' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'Upper-middle-income countries' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'World';

SELECT *
FROM Energyproject..['hydro-electricity-per-capita$']
WHERE Energyproject..['hydro-electricity-per-capita$'].Entity <> 'Africa' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'Asia' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'Central African Republic' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'Democratic Republic of Congo' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'Europe' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'European Union (27)' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'High-income countries' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'Hong Kong' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'Low-income countries' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'Lower-middle-income countries' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'North America' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'South America' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'Upper-middle-income countries' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'World';

SELECT *
FROM Energyproject..['nuclear-electricity-per-capita$']
WHERE Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'Africa' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'Asia' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'Central African Republic' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'Democratic Republic of Congo' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'Europe' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'European Union (27)' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'High-income countries' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'Hong Kong' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'Low-income countries' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'Lower-middle-income countries' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'North America' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'South America' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'Upper-middle-income countries' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'World';

SELECT *
FROM Energyproject..['oil-electricity-per-capita$']
WHERE Energyproject..['oil-electricity-per-capita$'].Entity <> 'Africa' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'Asia' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'Central African Republic' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'Democratic Republic of Congo' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'Europe' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'European Union (27)' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'High-income countries' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'Hong Kong' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'Low-income countries' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'Lower-middle-income countries' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'North America' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'South America' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'Upper-middle-income countries' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'World';

SELECT *
FROM Energyproject..['solar-electricity-per-capita$']
WHERE Energyproject..['solar-electricity-per-capita$'].Entity <> 'Africa' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'Asia' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'Central African Republic' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'Democratic Republic of Congo' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'Europe' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'European Union (27)' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'High-income countries' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'Hong Kong' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'Low-income countries' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'Lower-middle-income countries' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'North America' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'South America' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'Upper-middle-income countries' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'World';

SELECT *
FROM Energyproject..['wind-electricity-per-capita$']
WHERE Energyproject..['wind-electricity-per-capita$'].Entity <> 'Africa' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'Asia' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'Central African Republic' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'Democratic Republic of Congo' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'Europe' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'European Union (27)' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'High-income countries' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'Hong Kong' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'Low-income countries' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'Lower-middle-income countries' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'North America' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'South America' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'Upper-middle-income countries' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'World';

--finding the average and sum of energy per capita by location

SELECT Energyproject..['coal-electricity-per-capita$'].Entity, AVG(Energyproject..['coal-electricity-per-capita$'].[Coal electricity per capita (kWh)]) AS Avg_coal, SUM(Energyproject..['coal-electricity-per-capita$'].[Coal electricity per capita (kWh)]) AS SUM_coal 
FROM Energyproject..['coal-electricity-per-capita$']
WHERE Energyproject..['coal-electricity-per-capita$'].Entity <> 'Africa' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'Asia' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'Central African Republic' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'Democratic Republic of Congo' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'Europe' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'European Union (27)' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'High-income countries' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'Hong Kong' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'Low-income countries' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'Lower-middle-income countries' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'North America' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'South America' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'Upper-middle-income countries' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'World'
GROUP BY Energyproject..['coal-electricity-per-capita$'].Entity
ORDER BY Energyproject..['coal-electricity-per-capita$'].Entity;

SELECT Energyproject..['hydro-electricity-per-capita$'].Entity, AVG(Energyproject..['hydro-electricity-per-capita$'].[Hydro electricity per capita (kWh)]) AS Avg_hydro, SUM(Energyproject..['hydro-electricity-per-capita$'].[hydro electricity per capita (kWh)]) AS SUM_hydro 
FROM Energyproject..['hydro-electricity-per-capita$']
WHERE Energyproject..['hydro-electricity-per-capita$'].Entity <> 'Africa' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'Asia' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'Central African Republic' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'Democratic Republic of Congo' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'Europe' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'European Union (27)' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'High-income countries' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'Hong Kong' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'Low-income countries' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'Lower-middle-income countries' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'North America' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'South America' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'Upper-middle-income countries' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'World'
GROUP BY Energyproject..['hydro-electricity-per-capita$'].Entity
ORDER BY Energyproject..['hydro-electricity-per-capita$'].Entity;

SELECT Energyproject..['nuclear-electricity-per-capita$'].Entity, AVG(Energyproject..['nuclear-electricity-per-capita$'].[Nuclear electricity per capita (kWh)]) AS Avg_nuclear, SUM(Energyproject..['nuclear-electricity-per-capita$'].[nuclear electricity per capita (kWh)]) AS SUM_nuclear 
FROM Energyproject..['nuclear-electricity-per-capita$']
WHERE Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'Africa' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'Asia' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'Central African Republic' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'Democratic Republic of Congo' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'Europe' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'European Union (27)' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'High-income countries' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'Hong Kong' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'Low-income countries' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'Lower-middle-income countries' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'North America' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'South America' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'Upper-middle-income countries' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'World'
GROUP BY Energyproject..['nuclear-electricity-per-capita$'].Entity
ORDER BY Energyproject..['nuclear-electricity-per-capita$'].Entity;

SELECT Energyproject..['oil-electricity-per-capita$'].Entity, AVG(Energyproject..['oil-electricity-per-capita$'].[Oil electricity per capita (kWh)]) AS Avg_oil, SUM(Energyproject..['oil-electricity-per-capita$'].[oil electricity per capita (kWh)]) AS SUM_oil 
FROM Energyproject..['oil-electricity-per-capita$']
WHERE Energyproject..['oil-electricity-per-capita$'].Entity <> 'Africa' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'Asia' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'Central African Republic' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'Democratic Republic of Congo' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'Europe' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'European Union (27)' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'High-income countries' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'Hong Kong' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'Low-income countries' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'Lower-middle-income countries' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'North America' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'South America' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'Upper-middle-income countries' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'World'
GROUP BY Energyproject..['oil-electricity-per-capita$'].Entity
ORDER BY Energyproject..['oil-electricity-per-capita$'].Entity;

SELECT Energyproject..['solar-electricity-per-capita$'].Entity, AVG(Energyproject..['solar-electricity-per-capita$'].[Solar electricity per capita (kWh)]) AS Avg_solar, SUM(Energyproject..['solar-electricity-per-capita$'].[solar electricity per capita (kWh)]) AS SUM_solar 
FROM Energyproject..['solar-electricity-per-capita$']
WHERE Energyproject..['solar-electricity-per-capita$'].Entity <> 'Africa' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'Asia' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'Central African Republic' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'Democratic Republic of Congo' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'Europe' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'European Union (27)' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'High-income countries' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'Hong Kong' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'Low-income countries' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'Lower-middle-income countries' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'North America' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'South America' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'Upper-middle-income countries' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'World'
GROUP BY Energyproject..['solar-electricity-per-capita$'].Entity
ORDER BY Energyproject..['solar-electricity-per-capita$'].Entity;

SELECT Energyproject..['wind-electricity-per-capita$'].Entity, AVG(Energyproject..['wind-electricity-per-capita$'].[Wind electricity per capita (kWh)]) AS Avg_wind, SUM(Energyproject..['wind-electricity-per-capita$'].[wind electricity per capita (kWh)]) AS SUM_wind 
FROM Energyproject..['wind-electricity-per-capita$']
WHERE Energyproject..['wind-electricity-per-capita$'].Entity <> 'Africa' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'Asia' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'Central African Republic' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'Democratic Republic of Congo' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'Europe' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'European Union (27)' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'High-income countries' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'Hong Kong' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'Low-income countries' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'Lower-middle-income countries' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'North America' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'South America' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'Upper-middle-income countries' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'World'
GROUP BY Energyproject..['wind-electricity-per-capita$'].Entity
ORDER BY Energyproject..['wind-electricity-per-capita$'].Entity;

--Find Linear trends with average energy consumption w.r.t time.

SELECT Energyproject..['coal-electricity-per-capita$'].Year, AVG(Energyproject..['coal-electricity-per-capita$'].[Coal electricity per capita (kWh)]) AS Avg_coal, STDEV(cast(Energyproject..['coal-electricity-per-capita$'].[Coal electricity per capita (kWh)] as int))/10 AS StDev
FROM Energyproject..['coal-electricity-per-capita$']
WHERE Energyproject..['coal-electricity-per-capita$'].[Coal electricity per capita (kWh)] IS NOT NULL AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'Africa' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'Asia' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'Central African Republic' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'Democratic Republic of Congo' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'Europe' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'European Union (27)' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'High-income countries' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'Hong Kong' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'Low-income countries' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'Lower-middle-income countries' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'North America' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'South America' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'Upper-middle-income countries' AND Energyproject..['coal-electricity-per-capita$'].Entity <> 'World'
GROUP BY Energyproject..['coal-electricity-per-capita$'].Year
ORDER BY Energyproject..['coal-electricity-per-capita$'].Year;

SELECT Energyproject..['hydro-electricity-per-capita$'].Year, AVG(Energyproject..['hydro-electricity-per-capita$'].[Hydro electricity per capita (kWh)]) AS Avg_hydro, STDEV(cast(Energyproject..['hydro-electricity-per-capita$'].[hydro electricity per capita (kWh)] as int))/10 AS StDev
FROM Energyproject..['hydro-electricity-per-capita$']
WHERE Energyproject..['hydro-electricity-per-capita$'].[hydro electricity per capita (kWh)] IS NOT NULL AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'Africa' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'Asia' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'Central African Republic' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'Democratic Republic of Congo' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'Europe' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'European Union (27)' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'High-income countries' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'Hong Kong' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'Low-income countries' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'Lower-middle-income countries' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'North America' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'South America' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'Upper-middle-income countries' AND Energyproject..['hydro-electricity-per-capita$'].Entity <> 'World'
GROUP BY Energyproject..['hydro-electricity-per-capita$'].Year
ORDER BY Energyproject..['hydro-electricity-per-capita$'].Year;

SELECT Energyproject..['nuclear-electricity-per-capita$'].Year, AVG(Energyproject..['nuclear-electricity-per-capita$'].[Nuclear electricity per capita (kWh)]) AS Avg_nuclear, STDEV(cast(Energyproject..['nuclear-electricity-per-capita$'].[Nuclear electricity per capita (kWh)] as int))/10 AS StDev
FROM Energyproject..['nuclear-electricity-per-capita$']
WHERE Energyproject..['nuclear-electricity-per-capita$'].[Nuclear electricity per capita (kWh)] IS NOT NULL AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'Africa' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'Asia' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'Central African Republic' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'Democratic Republic of Congo' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'Europe' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'European Union (27)' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'High-income countries' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'Hong Kong' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'Low-income countries' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'Lower-middle-income countries' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'North America' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'South America' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'Upper-middle-income countries' AND Energyproject..['nuclear-electricity-per-capita$'].Entity <> 'World'
GROUP BY Energyproject..['nuclear-electricity-per-capita$'].Year
ORDER BY Energyproject..['nuclear-electricity-per-capita$'].Year;

SELECT Energyproject..['oil-electricity-per-capita$'].Year, AVG(Energyproject..['oil-electricity-per-capita$'].[Oil electricity per capita (kWh)]) AS Avg_oil, STDEV(cast(Energyproject..['oil-electricity-per-capita$'].[Oil electricity per capita (kWh)] as int))/10 AS StDev
FROM Energyproject..['oil-electricity-per-capita$']
WHERE Energyproject..['oil-electricity-per-capita$'].[Oil electricity per capita (kWh)] IS NOT NULL AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'Africa' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'Asia' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'Central African Republic' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'Democratic Republic of Congo' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'Europe' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'European Union (27)' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'High-income countries' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'Hong Kong' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'Low-income countries' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'Lower-middle-income countries' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'North America' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'South America' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'Upper-middle-income countries' AND Energyproject..['oil-electricity-per-capita$'].Entity <> 'World'
GROUP BY Energyproject..['oil-electricity-per-capita$'].Year
ORDER BY Energyproject..['oil-electricity-per-capita$'].Year;

SELECT Energyproject..['solar-electricity-per-capita$'].Year, AVG(cast(Energyproject..['solar-electricity-per-capita$'].[Solar electricity per capita (kWh)] as int)) AS Avg_solar, cast(STDEV(cast(Energyproject..['solar-electricity-per-capita$'].[Solar electricity per capita (kWh)] as int)) as int)/10 AS StDev
FROM Energyproject..['solar-electricity-per-capita$']
WHERE Energyproject..['solar-electricity-per-capita$'].[Solar electricity per capita (kWh)] IS NOT NULL AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'Africa' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'Asia' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'Central African Republic' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'Democratic Republic of Congo' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'Europe' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'European Union (27)' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'High-income countries' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'Hong Kong' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'Low-income countries' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'Lower-middle-income countries' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'North America' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'South America' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'Upper-middle-income countries' AND Energyproject..['solar-electricity-per-capita$'].Entity <> 'World' AND Energyproject..['solar-electricity-per-capita$'].Year >= 2011
GROUP BY Energyproject..['solar-electricity-per-capita$'].Year
ORDER BY Energyproject..['solar-electricity-per-capita$'].Year;

SELECT Energyproject..['wind-electricity-per-capita$'].Year, AVG(cast(Energyproject..['wind-electricity-per-capita$'].[Wind electricity per capita (kWh)] as int)) AS Avg_wind, cast(STDEV(cast(Energyproject..['wind-electricity-per-capita$'].[Wind electricity per capita (kWh)] as int)) as int)/10 AS StDev
FROM Energyproject..['wind-electricity-per-capita$']
WHERE Energyproject..['wind-electricity-per-capita$'].[Wind electricity per capita (kWh)] IS NOT NULL AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'Africa' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'Asia' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'Central African Republic' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'Democratic Republic of Congo' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'Europe' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'European Union (27)' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'High-income countries' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'Hong Kong' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'Low-income countries' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'Lower-middle-income countries' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'North America' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'South America' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'Upper-middle-income countries' AND Energyproject..['wind-electricity-per-capita$'].Entity <> 'World' AND Energyproject..['wind-electricity-per-capita$'].Year >= 2000
GROUP BY Energyproject..['wind-electricity-per-capita$'].Year
ORDER BY Energyproject..['wind-electricity-per-capita$'].Year;